name: Deploy to staging

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploy everything to staging server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_deploy
          chmod 600 ~/.ssh/id_rsa_deploy  
          ssh-keyscan -H 139.59.87.169 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa_deploy root@139.59.87.169 << 'EOF'
            export PATH=$PATH:/root/.local/share/pnpm:/root/.nvm/versions/node/$(node -v)/bin
            cd /root/BMS
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart http-server
            pm2 restart ws-server
            pm2 restart web
          EOF